import type { NextPage } from "next";
import Head from "next/head";
import Intro from "./home/intro";
import About from "./home/about";
import Skills from "./home/skills";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>developd | programmed to perfection.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <About />
      <Skills />
    </div>
  );
};

export default Home;
